import food1 from "../assets/food1.jpeg";

export const postData = [
  {
    username: "Lara Leones",
    userHandle: "@thewallart",
    content: "Foodie!",
    imageUrl: food1,
    likes: "9.8k",
    comments: "8.6k",
    shares: "7.2k",
  },
  {
    username: "John Smith",
    userHandle: "@johnsmith98",
    content: "Today, I learned something new!  #coding #javascript",
    imageUrl: "",
    likes: "2.1k",
    comments: "157",
    shares: "82",
  },
  {
    username: "Foodie Friends",
    userHandle: "@foodiefriends",
    content: "Check out this delicious recipe for homemade pizza!",
    imageUrl: "",
    likes: "4.3k",
    comments: "321",
    shares: "1.8k",
  },
  {
    username: "Nature Lover",
    userHandle: "@nature_enthusiast",
    content: "Exploring the beauty of a hidden waterfall ️",
    imageUrl: "https://unsplash.com/s/photos/waterfall",
    likes: "1.2k",
    comments: "98",
    shares: "412",
  },
  {
    username: "Bookworm",
    userHandle: "@bibliophile_life",
    content: "Just finished this amazing novel, highly recommend! ",
    imageUrl: "",
    likes: "789",
    comments: "123",
    shares: "34",
  },
  {
    username: "Travelholic",
    userHandle: "@globetrotter_diaries",
    content: "Sunsets are the best part of any trip! ",
    imageUrl: "",
    likes: "3.5k",
    comments: "274",
    shares: "618",
  },
  {
    username: "Fitness Fanatic",
    userHandle: "@getfit_2024",
    content: "Completed my morning run! Feeling energized  #fitnessjourney",
    imageUrl: "https://media.istockphoto.com/id/1324624694/photo/fitness-woman-running-training-for-marathon-on-sunny-coast-trail.jpg?s=612x612&w=0&k=20&c=09StrnZiVdHvfR1G9CeBqcMYxSvFSGFQVuNbOzhBQ-c=",
    likes: "1.8k",
    comments: "142",
    shares: "97",
  },
  {
    username: "Gamer Zone",
    userHandle: "@ultimate_gamer",
    content: "Just beat the final boss, so satisfying!  #gaminglife",
    imageUrl: "https://t4.ftcdn.net/jpg/05/71/19/05/360_F_571190572_EyjlzUbpoUpfbOVsi1gT7njTBELh5TL2.jpg",
    likes: "4.1k",
    comments: "523",
    shares: "789",
  },
  {
    username: "DIY Crafts",
    userHandle: "@handmade_withlove",
    content: "Finished this cute knitted scarf, perfect for fall!  #crafts",
    imageUrl: "",
    likes: "2.7k",
    comments: "418",
    shares: "324",
  },
  {
    username: "Music Maestro",
    userHandle: "@melodies_for_life",
    content: "Obsessed with this new song, can't stop listening! #musiclover",
    imageUrl: "",
    likes: "3.9k",
    comments: "214",
  },
  {
    username: "Pet Paradise",
    userHandle: "@furry_friends",
    content: "My cat is the cutest thing ever!  #catsofinstagram",
    imageUrl: "https://cdn.pixabay.com/photo/2024/03/07/10/38/simba-8618301_1280.jpg",
    likes: "5.2k",
    comments: "872",
    shares: "1.4k",
  },
];
